shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("store.urls", namespace="store"))
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views


app_name = "store"

urlpatterns = [
    path("", views.store, name="store"),
    path("cart/", views.cart, name="cart"),
    path("checkout/", views.checkout, name="checkout"),
    path("update_item/", views.updateItem, name="update_item"),
    path("process_order/", views.processOrder, name="process_order"),
]

store/models.py
from django.db import models
from django.contrib.auth.models import User


class Customer(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=200, null=True)
    price = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    digital = models.BooleanField(default=False, null=True, blank=False)
    image = models.ImageField(null=True)

    def __str__(self):
        return self.name

    @property
    def imageurl(self):
        try:
            url = self.image.url
        except:
            url = ""
        return url


class Order(models.Model):
    customer = models.ForeignKey(Customer, null=True, blank=True, on_delete=models.SET_NULL)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=False)
    transaction_id = models.CharField(max_length=200, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def shipping(self):
        shipping = False
        orderitem = self.orderitem_set.all()

        for i in orderitem:
            if i.product.digital == False:
                shipping = True

        return shipping


    @property
    def get_cart_total(self):
        orderitem = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitem])
        return total

    @property
    def get_cart_item(self):
        orderitem = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitem])
        return total



class OrderItem(models.Model):
    product = models.ForeignKey(Product, null=True, on_delete=models.SET_NULL)
    order = models.ForeignKey(Order, null=True, on_delete=models.SET_NULL)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_ordered = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total


class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, null=True, blank=True, on_delete=models.SET_NULL)
    order = models.ForeignKey(Order, null=True, on_delete=models.SET_NULL)
    address = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=200, null=True)
    state = models.CharField(max_length=200, null=True)
    zipcode = models.CharField(max_length=200, null=True)
    date_ordered = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

store/views.py
from django.shortcuts import render
from .models import *
from django.http import JsonResponse
import datetime
import json
from .utils import cookieCart, cartData, guestOrder


def store(request):
    data = cartData(request)
    cart_items = data["cart_items"]


    products = Product.objects.all()
    context = {"products": products, "cart_items": cart_items}
    return render(request, "store/store.html", context)


def cart(request):
    data = cartData(request)
    cart_items = data["cart_items"]
    order = data["order"]
    items = data["items"]

    context = {"items": items, "order": order, "cart_items": cart_items}
    return render(request, "store/cart.html", context)


def checkout(request):

    data = cartData(request)
    cart_items = data["cart_items"]
    order = data["order"]
    items = data["items"]

    context = {"items": items, "order": order, "cart_items": cart_items}
    return render(request, "store/checkout.html", context)


def updateItem(request):
    data = json.loads(request.body)
    action = data["action"]
    productId = data["productId"]



    customer = request.user.customer
    product = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(customer=customer, complete=False)
    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

    if action == "add":
        orderItem.quantity = (orderItem.quantity + 1)
    elif action == "remove":
        orderItem.quantity = (orderItem.quantity - 1)

    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete()

    return JsonResponse("Item was added", safe=False)


def processOrder(request):
   transaction_id = datetime.datetime.now().timestamp()
   data = json.loads(request.body)

   if request.user.is_authenticated:
       customer = request.user.customer
       order, created = Order.objects.get_or_create(customer=customer, complete=False)



   else:
       customer, order = guestOrder(request, data)

   total = float(data["form"]["total"])
   order.transaction_id = transaction_id

   if total == order.get_cart_total:
       order.complete = True
   order.save()

   if order.shipping == True:
       ShippingAddress.objects.create(
           customer=customer,
           order=order,
           address=data["shipping"]["address"],
           city=data["shipping"]["city"],
           state=data["shipping"]["state"],
           zipcode=data["shipping"]["zipcode"],
       )

   return JsonResponse("Payment complete!", safe=False)

store/templates/store/base.html
{% load static %}
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">


	<script type="text/javascript">
		var user = "{{request.user}}"

		function getToken(name) {
			let cookieValue = null;
			if (document.cookie && document.cookie !== '') {
				const cookies = document.cookie.split(';');
				for (let i = 0; i < cookies.length; i++) {
					const cookie = cookies[i].trim();
					// Does this cookie string begin with the name we want?
					if (cookie.substring(0, name.length + 1) === (name + '=')) {
						cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
						break;
					}
				}
			}
			return cookieValue;
		}
		const csrftoken = getToken('csrftoken');


		function getCookie(name){
			var cookieArr = document.cookie.split(";");

			for (var i = 0; i < cookieArr.length; i++){
				var cookiePair = cookieArr[i].split("=");

				if(name == cookiePair[0].trim()){
					return decodeURIComponent(cookiePair[1]);
				}
			}

			return null;
		}

		var cart = JSON.parse(getCookie("cart"))
		if(cart == undefined){
			cart = {}
			console.log("Cart was created!")
			document.cookie = "cart=" + JSON.stringify(cart) + ";domain=;path=/"
		}

		console.log("Cart:", cart)
	</script>

    <title>Title</title>
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	  <a class="navbar-brand" href="{% url 'store:store' %}">Ecom</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">
	      <li class="nav-item active">
	        <a class="nav-link" href="{% url 'store:store' %}">Store</a>
	      </li>
	    </ul>
		<div class="form-inline my-2 my-lg-0">
			<a href="#" class="btn btn-warning">Login</a>

			<a href="{% url 'store:cart' %}">
				<img id="cart-icon" src="{% static 'images/cart.png' %}">
			</a>
			<p id="cart-total">{{cart_items}}</p>
		</div>
	  </div>
	</nav>

	<div class="container">
		{% block content %}

    	{% endblock %}
	</div>



<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<script type="text/javascript" src="{% static 'js/cart.js' %}"></script>

</body>
</html>

store/templates/store/cart.html
{% extends 'store/base.html' %}
{% load static %}


{% block content %}
<div class="row">
    <div class="col-lg-12">
        <div class="box-element">
            <a class="btn btn-outline-dark" href="{% url 'store:store' %}">&#x2190; Continue Shopping</a>
            <br>
            <br>


            <table class="table">
                <tr>
                    <th><h5>Items: <strong>{{order.get_cart_item}}</strong></h5></th>
                    <th><h5>Total: <strong>${{order.get_cart_total}}</strong></h5></th>
                    <th>
                        <a style="float: right; margin: 5px;" class="btn btn-success" href="{% url 'store:checkout' %}">Checkout</a>
                    </th>
                </tr>
            </table>


        </div>

        <br>

        <div class="box-element">
            <div class="cart-row">
                <div style="flex:2"></div>
                <div style="flex:2"><strong>Item</strong></div>
                <div style="flex:1"><strong>Price</strong></div>
                 <div style="flex:1"><strong>Quantity</strong></div>
                 <div style="flex:1"><strong>Total</strong></div>
            </div>

            {% for item in items %}
            <div class="cart-row">
                <div style="flex:2"><img class="row-image" src="{{item.product.imageurl}}"></div>
                <div style="flex:2">{{item.product.name}}</div>
                <div style="flex:1">${{item.product.price}}</div>
                 <div style="flex:1">
                     <p class="quantity">{{item.quantity}}</p>
                     <div class="quantity">
                         <img data-product={{item.product.id}} data-action="add" class="chg-quantity update-cart" src="{% static 'images/arrow-up.png' %}">

                         <img data-product={{item.product.id}} data-action="remove" class="chg-quantity update-cart" src="{% static 'images/arrow-down.png' %}">
                     </div>
                 </div>
                 <div style="flex:1">${{item.get_total}}</div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

store/templates/store/checkout.html
{% extends 'store/base.html' %}
{% load static %}


{% block content %}
    <div class="row">
        <div class="col-lg-6">
            <div class="box-element" id="form-wrapper">
                <form id="form">
                    <div id="user-info">
                        <div class="form-field">
                            <input required class="form-control" type="text" name="name" placeholder="Name...">
                        </div>
                        <div class="form-field">
                            <input required class="form-control" type="text" name="email" placeholder="Email...">
                        </div>
                    </div>

                    <div id="shipping-info">
                        <hr>
                        <p>Shipping Information</p>
                        <hr>
                        <div class="form-field">
                            <input required class="form-control" type="text" name="address" placeholder="Address...">
                        </div>
                        <div class="form-field">
                            <input required class="form-control" type="text" name="city" placeholder="City...">
                        </div>
                        <div class="form-field">
                            <input required class="form-control" type="text" name="state" placeholder="State...">
                        </div>
                        <div class="form-field">
                            <input required class="form-control" type="text" name="zipcode" placeholder="Zip code...">
                        </div>
                        <div class="form-field">
                            <input required class="form-control" type="text" name="zipcode" placeholder="Country...">
                        </div>


                    </div>

                    <hr>
                    <input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
                </form>
            </div>
            <br>
            <div class="box-element hidden" id="payment-info">
                <small>Paypal Options</small>
                <div id="paypal-button-container"></div>
                <!--<button id="make-payment">Make Payment</button>-->
            </div>
        </div>


        <div class="col-lg-6">
            <div class="box-element">
                <a class="btn btn-outline-dark" href="{% url 'store:cart' %}">&#x2190; Back to Cart</a>
                <hr>
                <h3>Order Summary</h3>
                <hr>
                {% for item in items %}
                <div class="cart-row">
                    <div style="flex:2"><img class="row-image" src="{{item.product.imageurl}}"></div>
                    <div style="flex:2">{{item.product.name}}</div>
                    <div style="flex:1">${{item.product.price}}</div>
                    <div style="flex:1">x{{item.quantity}}</div>
                </div>
                {% endfor %}

                <h5>Items: {{order.get_cart_item}}</h5>
                <h5>Total: ${{order.get_cart_total}}</h5>
            </div>
        </div>
    </div>

<script src="https://www.paypal.com/sdk/js?client-id=AdPCT1lxZlo-stcJps5cgXX93hBHgs_sCbByG-8eA1JgskxXyxX-syS0jHHwuckrHDDjSgidhg-G4bRE&currency=USD"></script>

<script>

        var total = '{{order.get_cart_total}}'
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({

            style:{
                color:"blue",
                shape:"rect",
            },

            // Set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: parseFloat(total).toFixed(2)
                        }
                    }]
                });
            },

            // Finalize the transaction
            onApprove: function(data, actions) {
                return actions.order.capture().then(function(details) {
                    submitFormData()
                });
            }


        }).render('#paypal-button-container');
</script>

<script type="text/javascript">
    var shipping = "{{order.shipping}}"


    if(shipping == "False"){
        document.getElementById("shipping-info").innerHTML = ""
    }

    if (user != 'AnonymousUser'){
        document.getElementById("user-info").innerHTML = ""
    }

    if (shipping == 'False' && user != 'AnonymousUser'){
        document.getElementById('form-wrapper').classList.add('hidden')
        document.getElementById('payment-info').classList.remove('hidden')
    }

    var form = document.getElementById("form")

    form.addEventListener('submit', function(e){
        e.preventDefault()
        console.log('Form submitted...')
        document.getElementById('form-button').classList.add('hidden')
        document.getElementById('payment-info').classList.remove('hidden')
    })

    /*
    document.getElementById('make-payment').addEventListener('click', function(e){
        submitFormData()
    })
    */

    function submitFormData(){
        console.log('Payment button clicked')

        var userFormData = {
            'name':null,
            'email':null,
            'total':total
        }

        var shippingInfo = {
            'address':null,
            'city':null,
            'state':null,
            'zipcode':null
        }

        if (shipping != 'False'){
            shippingInfo.address = form.address.value
            shippingInfo.city = form.city.value
            shippingInfo.state = form.state.value
            shippingInfo.zipcode = form.zipcode.value
        }

        if (user == 'AnonymousUser'){
            userFormData.name = form.name.value
            userFormData.email = form.email.value
        }

        console.log('shippinginfo:', shippingInfo)
        console.log('usrformdata:', userFormData)

        var url = "/process_order/"

        fetch(url, {

            method: "POST",
            headers:{
                "Content-Type":"application/json",
                "X-CSRFToken":csrftoken,
            },
            body:JSON.stringify({"form":userFormData, "shipping":shippingInfo})
        })
        .then((response) => response.json())

        .then((data) => {
            console.log("Success:", data);
            alert("Transaction completed");

            cart = {}
            document.cookie = "cart=" + JSON.stringify(cart) + ";domain=;path=/"
            window.location.href = "{% url 'store:store' %}"
        })
    }
</script>
{% endblock %}

store/templates/store/store.html
{% extends 'store/base.html' %} 
{% load static %}


{% block content %}
    <div class="row">
        {% for product in products %}
        <div class="col-lg-4">
            <img class="thumbnail" src="{{product.imageurl}}">
            <div class="box-element product">
                <h6><strong>{{product.name}}</strong></h6>
                <hr>
                <button data-product="{{product.id}}" data-action="add" class="btn btn-outline-secondary add-btn update-cart">Add to Cart</button>
                <a class="btn btn-outline-success" href="#">View</a>
                <h4 style="display: inline-block; float: right;">${{product.price}}</h4>
            </div>
        </div>
        {% endfor %}
    </div>

{% endblock %}